### ISSUE TITLE
[Question] iOS dependency manager usage choice concerns

### ISSUE THREAD

**Issue by minhnimble** [nguyenvhung9420/survey-app-hungnguy#3]
## Issue

Currently, I notice that you are using both `Swift Package Manager` and `CocoaPods` for handling the dependencies for the iOS project. Can you tell me a little bit more on why you choose to use a mix of dependency managers like this? and what are the benefits that this approach can provide compare to using one dependency manager only?

**Comment by nguyenvhung9420** [comment]
Ok, in this project, I was using at the same time two dependency managers which are Swift Package Manager and Cocoapods. 

In Swift Package Manager, the main reason I choose to get Apollo GraphQL from this manager is its stability, based on my latest experience of using this library from the latest project that was using GraphQL. I have tried to download Apollo from Cocoapods but it was not stable and was generating some annoying errors related to SQLite: when choosing Apollo from SPM, it also lets me to choose to install ApolloSQL, with Cocoapods, it did not offer this selection and we tried hours how to add ApolloSQL separately.

Anyway, back to the question that we should or should not use at the same time 2 managers, I may not be very diving deeper into this technical question because, until now, it has not yet posed for me any technical issues, at least serious ones. Personally if I was in a small or demo project, I will choose to use SPM because of some advantages. The libraries which are managed with SPM is stable because it prevents any modifications from outside. Furthermore, the libs will be automatically fetched when opening the “.xcproject” file. The installation of new library with SPM is totally observed by Xcode with GUI so it takes the job in the more practical way than with Cocoapods.

Cocoapods was being chosen my many ones but sometime I see some problems with it. It need to be reinstalled whenever cloning the project, and of course, version conflicts with Swift (and with M1 chip, with Cocoapods version) are inevitable. Cocoapods creates a so-called “Pods” project alongside with our main one in the workspace and, sometimes, I experienced the errors of non-matching iOS target which prevents the project to be built.

However, the number of library which are built and published on Cocoapods are far more than on SPM or Carthage; so I think for longterm development of a project, Cocoapods should be used.
